spring:
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8081"
        instance:
          prefer-ip: true
          name: ${spring.application.name}
#          metadata:
#            # post info to server
#            user:
#              name: root
#              password: root
        username: root
        password: root
  application:
    name: gateway
#  security:
#    user:
#      name: root
#      password: root

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
